batch_size: 256
beta: 3.0
buffer_size: 2000000
checkpoints_path: ./models/iql_8171282
device: cuda
discount: 0.99
env: halfcheetah-medium-v2
eval_freq: 20000
group: IQL-tau07-halfcheetah-medium-v2
iql_deterministic: false
iql_tau: 0.7
load_model: ''
max_finetunestep: 500000
max_timesteps: 500000
n_episodes: 100
name: IQL-8171282
normalize: true
normalize_reward: false
project: CORL
seed: 8171282
tau: 0.005
